---
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        update: yes
        cache_valid_time: 3600    # 1 hour

    - name: Install Binaries
      ansible.builtin.apt:
        name: 
          - cmatrix
          - ansible
          - git
          - python3
          - python3-pip
          - net-tools
          - tftp-hpa
        state: present
      become: true 