---
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Install cmatrix
      ansible.builtin.apt:
        name: cmatrix
        state: present
      become: true 

    - name: Ensure Nginx service is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      become: true